name: "Deploy to GitHub Pages"

# build & publish on every push to main
on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          # gh-pages action will push to gh-pages branch, so
          # avoid the default token being deleted by checkout
          persist-credentials: false

      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: "Install dependencies"
        run: npm ci

      - name: "Configure git identity"
        run: |
          # gh-pages will create commits; make sure git has a valid user/email
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: "Build & deploy"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run predeploy
          npm run deploy
